### ISSUE TITLE
Please fix bugtracker link

### ISSUE THREAD

**Issue by pcav** [jicrbuh/CoordinateGuesser#1]
It currently points nowhere.
Thanks.

**Comment by jicrbuh** [comment]
Hi,
I updated the bugtracker to https://github.com/jicrbuh/CoordinateGuesser/issues

**Comment by pcav** [comment]
Not confirmed: on plugins.qgis.org the link is still wrong.
thanks

**Comment by jicrbuh** [comment]
It's updated in plugins.qgis.org now too
